// Donor → HAS_CLUSTER_PCT → CellCluster
// 생성: bisect_to_neo4j.py

// ─── HAS_CLUSTER_PCT 관계 (Donor → CellCluster) ────────────
// 속성: pct(%), n_cells, condition

MATCH (n:Donor {donor_id: 'PO05'}) MATCH (c:CellCluster {leiden_id: 18}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.586884, r.n_cells = 23, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'PO11'}) MATCH (c:CellCluster {leiden_id: 18}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.738526, r.n_cells = 75, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'PO13'}) MATCH (c:CellCluster {leiden_id: 18}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.79602, r.n_cells = 16, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'PO15'}) MATCH (c:CellCluster {leiden_id: 18}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.653696, r.n_cells = 34, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'PO20'}) MATCH (c:CellCluster {leiden_id: 18}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.010101, r.n_cells = 39, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'PO23'}) MATCH (c:CellCluster {leiden_id: 18}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.483229, r.n_cells = 17, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'PO28'}) MATCH (c:CellCluster {leiden_id: 18}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 3.39663, r.n_cells = 127, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'PO41'}) MATCH (c:CellCluster {leiden_id: 18}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 2.661597, r.n_cells = 70, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'PO42'}) MATCH (c:CellCluster {leiden_id: 18}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.400906, r.n_cells = 68, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC027'}) MATCH (c:CellCluster {leiden_id: 18}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.0, r.n_cells = 0, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'SMC029'}) MATCH (c:CellCluster {leiden_id: 18}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.107009, r.n_cells = 2, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC030'}) MATCH (c:CellCluster {leiden_id: 18}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.702138, r.n_cells = 45, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'SMC031'}) MATCH (c:CellCluster {leiden_id: 18}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.653026, r.n_cells = 15, r.condition = 'Active control';
MATCH (n:Donor {donor_id: 'SMC032'}) MATCH (c:CellCluster {leiden_id: 18}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.910902, r.n_cells = 32, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC033'}) MATCH (c:CellCluster {leiden_id: 18}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.04424, r.n_cells = 93, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'SMC035'}) MATCH (c:CellCluster {leiden_id: 18}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.143689, r.n_cells = 55, r.condition = 'Active control';
MATCH (n:Donor {donor_id: 'SMC036'}) MATCH (c:CellCluster {leiden_id: 18}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 2.186312, r.n_cells = 23, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC037'}) MATCH (c:CellCluster {leiden_id: 18}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.62963, r.n_cells = 55, r.condition = 'Active control';
MATCH (n:Donor {donor_id: 'SMC038'}) MATCH (c:CellCluster {leiden_id: 18}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.99889, r.n_cells = 36, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC039'}) MATCH (c:CellCluster {leiden_id: 18}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 5.555556, r.n_cells = 102, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC041'}) MATCH (c:CellCluster {leiden_id: 18}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 3.70765, r.n_cells = 174, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC043'}) MATCH (c:CellCluster {leiden_id: 18}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.470958, r.n_cells = 6, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC049'}) MATCH (c:CellCluster {leiden_id: 18}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 3.604422, r.n_cells = 238, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC052'}) MATCH (c:CellCluster {leiden_id: 18}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.651842, r.n_cells = 130, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'SMC053'}) MATCH (c:CellCluster {leiden_id: 18}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 2.692469, r.n_cells = 128, r.condition = 'Active control';
MATCH (n:Donor {donor_id: 'PO05'}) MATCH (c:CellCluster {leiden_id: 19}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.046185, r.n_cells = 41, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'PO11'}) MATCH (c:CellCluster {leiden_id: 19}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.440427, r.n_cells = 19, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'PO13'}) MATCH (c:CellCluster {leiden_id: 19}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 5.671642, r.n_cells = 114, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'PO15'}) MATCH (c:CellCluster {leiden_id: 19}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.972763, r.n_cells = 20, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'PO20'}) MATCH (c:CellCluster {leiden_id: 19}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 4.454804, r.n_cells = 172, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'PO23'}) MATCH (c:CellCluster {leiden_id: 19}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.73394, r.n_cells = 61, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'PO28'}) MATCH (c:CellCluster {leiden_id: 19}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.711688, r.n_cells = 64, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'PO41'}) MATCH (c:CellCluster {leiden_id: 19}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 2.471483, r.n_cells = 65, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'PO42'}) MATCH (c:CellCluster {leiden_id: 19}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.071281, r.n_cells = 52, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC027'}) MATCH (c:CellCluster {leiden_id: 19}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.348432, r.n_cells = 6, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'SMC029'}) MATCH (c:CellCluster {leiden_id: 19}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.053505, r.n_cells = 1, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC030'}) MATCH (c:CellCluster {leiden_id: 19}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.56171, r.n_cells = 36, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'SMC031'}) MATCH (c:CellCluster {leiden_id: 19}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.391815, r.n_cells = 9, r.condition = 'Active control';
MATCH (n:Donor {donor_id: 'SMC032'}) MATCH (c:CellCluster {leiden_id: 19}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.19926, r.n_cells = 7, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC033'}) MATCH (c:CellCluster {leiden_id: 19}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 3.660454, r.n_cells = 326, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'SMC035'}) MATCH (c:CellCluster {leiden_id: 19}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.977334, r.n_cells = 47, r.condition = 'Active control';
MATCH (n:Donor {donor_id: 'SMC036'}) MATCH (c:CellCluster {leiden_id: 19}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.045627, r.n_cells = 11, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC037'}) MATCH (c:CellCluster {leiden_id: 19}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.918519, r.n_cells = 31, r.condition = 'Active control';
MATCH (n:Donor {donor_id: 'SMC038'}) MATCH (c:CellCluster {leiden_id: 19}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.416204, r.n_cells = 15, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC039'}) MATCH (c:CellCluster {leiden_id: 19}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.381264, r.n_cells = 7, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC041'}) MATCH (c:CellCluster {leiden_id: 19}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.852333, r.n_cells = 40, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC043'}) MATCH (c:CellCluster {leiden_id: 19}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.078493, r.n_cells = 1, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC049'}) MATCH (c:CellCluster {leiden_id: 19}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.272603, r.n_cells = 18, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC052'}) MATCH (c:CellCluster {leiden_id: 19}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.550191, r.n_cells = 122, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'SMC053'}) MATCH (c:CellCluster {leiden_id: 19}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 2.629365, r.n_cells = 125, r.condition = 'Active control';
MATCH (n:Donor {donor_id: 'PO05'}) MATCH (c:CellCluster {leiden_id: 9}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.684103, r.n_cells = 66, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'PO11'}) MATCH (c:CellCluster {leiden_id: 9}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.112656, r.n_cells = 48, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'PO13'}) MATCH (c:CellCluster {leiden_id: 9}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.497512, r.n_cells = 10, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'PO15'}) MATCH (c:CellCluster {leiden_id: 9}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 2.140078, r.n_cells = 44, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'PO20'}) MATCH (c:CellCluster {leiden_id: 9}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.036001, r.n_cells = 40, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'PO23'}) MATCH (c:CellCluster {leiden_id: 9}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 3.013076, r.n_cells = 106, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'PO28'}) MATCH (c:CellCluster {leiden_id: 9}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.337256, r.n_cells = 50, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'PO41'}) MATCH (c:CellCluster {leiden_id: 9}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 2.053232, r.n_cells = 54, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'PO42'}) MATCH (c:CellCluster {leiden_id: 9}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.350227, r.n_cells = 17, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC027'}) MATCH (c:CellCluster {leiden_id: 9}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.858304, r.n_cells = 32, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'SMC029'}) MATCH (c:CellCluster {leiden_id: 9}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.374532, r.n_cells = 7, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC030'}) MATCH (c:CellCluster {leiden_id: 9}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 8.72211, r.n_cells = 559, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'SMC031'}) MATCH (c:CellCluster {leiden_id: 9}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.872007, r.n_cells = 43, r.condition = 'Active control';
MATCH (n:Donor {donor_id: 'SMC032'}) MATCH (c:CellCluster {leiden_id: 9}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 3.529747, r.n_cells = 124, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC033'}) MATCH (c:CellCluster {leiden_id: 9}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 3.750281, r.n_cells = 334, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'SMC035'}) MATCH (c:CellCluster {leiden_id: 9}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 3.389478, r.n_cells = 163, r.condition = 'Active control';
MATCH (n:Donor {donor_id: 'SMC036'}) MATCH (c:CellCluster {leiden_id: 9}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.425856, r.n_cells = 15, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC037'}) MATCH (c:CellCluster {leiden_id: 9}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.925926, r.n_cells = 65, r.condition = 'Active control';
MATCH (n:Donor {donor_id: 'SMC038'}) MATCH (c:CellCluster {leiden_id: 9}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 5.466149, r.n_cells = 197, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC039'}) MATCH (c:CellCluster {leiden_id: 9}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 2.069717, r.n_cells = 38, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC041'}) MATCH (c:CellCluster {leiden_id: 9}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 3.132325, r.n_cells = 147, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC043'}) MATCH (c:CellCluster {leiden_id: 9}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.078493, r.n_cells = 1, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC049'}) MATCH (c:CellCluster {leiden_id: 9}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 3.180373, r.n_cells = 210, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC052'}) MATCH (c:CellCluster {leiden_id: 9}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 5.120712, r.n_cells = 403, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'SMC053'}) MATCH (c:CellCluster {leiden_id: 9}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.914178, r.n_cells = 91, r.condition = 'Active control';
MATCH (n:Donor {donor_id: 'PO05'}) MATCH (c:CellCluster {leiden_id: 15}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 2.092371, r.n_cells = 82, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'PO11'}) MATCH (c:CellCluster {leiden_id: 15}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.34446, r.n_cells = 58, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'PO13'}) MATCH (c:CellCluster {leiden_id: 15}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.845771, r.n_cells = 17, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'PO15'}) MATCH (c:CellCluster {leiden_id: 15}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.750973, r.n_cells = 36, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'PO20'}) MATCH (c:CellCluster {leiden_id: 15}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.4403, r.n_cells = 17, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'PO23'}) MATCH (c:CellCluster {leiden_id: 15}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.307561, r.n_cells = 46, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'PO28'}) MATCH (c:CellCluster {leiden_id: 15}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.337256, r.n_cells = 50, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'PO41'}) MATCH (c:CellCluster {leiden_id: 15}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 2.661597, r.n_cells = 70, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'PO42'}) MATCH (c:CellCluster {leiden_id: 15}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.689328, r.n_cells = 82, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC027'}) MATCH (c:CellCluster {leiden_id: 15}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.58072, r.n_cells = 10, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'SMC029'}) MATCH (c:CellCluster {leiden_id: 15}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.321027, r.n_cells = 6, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC030'}) MATCH (c:CellCluster {leiden_id: 15}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.357466, r.n_cells = 87, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'SMC031'}) MATCH (c:CellCluster {leiden_id: 15}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.654332, r.n_cells = 38, r.condition = 'Active control';
MATCH (n:Donor {donor_id: 'SMC032'}) MATCH (c:CellCluster {leiden_id: 15}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 6.063194, r.n_cells = 213, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC033'}) MATCH (c:CellCluster {leiden_id: 15}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.639344, r.n_cells = 146, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'SMC035'}) MATCH (c:CellCluster {leiden_id: 15}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.975463, r.n_cells = 95, r.condition = 'Active control';
MATCH (n:Donor {donor_id: 'SMC036'}) MATCH (c:CellCluster {leiden_id: 15}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.901141, r.n_cells = 20, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC037'}) MATCH (c:CellCluster {leiden_id: 15}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 5.718519, r.n_cells = 193, r.condition = 'Active control';
MATCH (n:Donor {donor_id: 'SMC038'}) MATCH (c:CellCluster {leiden_id: 15}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 3.412875, r.n_cells = 123, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC039'}) MATCH (c:CellCluster {leiden_id: 15}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 2.614379, r.n_cells = 48, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC041'}) MATCH (c:CellCluster {leiden_id: 15}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 3.494566, r.n_cells = 164, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC043'}) MATCH (c:CellCluster {leiden_id: 15}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.706436, r.n_cells = 9, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC049'}) MATCH (c:CellCluster {leiden_id: 15}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 2.635166, r.n_cells = 174, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC052'}) MATCH (c:CellCluster {leiden_id: 15}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 2.426938, r.n_cells = 191, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'SMC053'}) MATCH (c:CellCluster {leiden_id: 15}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 2.56626, r.n_cells = 122, r.condition = 'Active control';
MATCH (n:Donor {donor_id: 'PO05'}) MATCH (c:CellCluster {leiden_id: 11}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 4.490942, r.n_cells = 176, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'PO11'}) MATCH (c:CellCluster {leiden_id: 11}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 4.149281, r.n_cells = 179, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'PO13'}) MATCH (c:CellCluster {leiden_id: 11}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 4.477612, r.n_cells = 90, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'PO15'}) MATCH (c:CellCluster {leiden_id: 11}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 3.988327, r.n_cells = 82, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'PO20'}) MATCH (c:CellCluster {leiden_id: 11}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 5.464905, r.n_cells = 211, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'PO23'}) MATCH (c:CellCluster {leiden_id: 11}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 5.25867, r.n_cells = 185, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'PO28'}) MATCH (c:CellCluster {leiden_id: 11}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 9.521262, r.n_cells = 356, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'PO41'}) MATCH (c:CellCluster {leiden_id: 11}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 5.893536, r.n_cells = 155, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'PO42'}) MATCH (c:CellCluster {leiden_id: 11}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 2.451586, r.n_cells = 119, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC027'}) MATCH (c:CellCluster {leiden_id: 11}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.348432, r.n_cells = 6, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'SMC029'}) MATCH (c:CellCluster {leiden_id: 11}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.481541, r.n_cells = 9, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC030'}) MATCH (c:CellCluster {leiden_id: 11}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.029802, r.n_cells = 66, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'SMC031'}) MATCH (c:CellCluster {leiden_id: 11}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.565956, r.n_cells = 13, r.condition = 'Active control';
MATCH (n:Donor {donor_id: 'SMC032'}) MATCH (c:CellCluster {leiden_id: 11}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 2.277256, r.n_cells = 80, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC033'}) MATCH (c:CellCluster {leiden_id: 11}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 3.772737, r.n_cells = 336, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'SMC035'}) MATCH (c:CellCluster {leiden_id: 11}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 3.264712, r.n_cells = 157, r.condition = 'Active control';
MATCH (n:Donor {donor_id: 'SMC036'}) MATCH (c:CellCluster {leiden_id: 11}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 1.045627, r.n_cells = 11, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC037'}) MATCH (c:CellCluster {leiden_id: 11}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 6.044444, r.n_cells = 204, r.condition = 'Active control';
MATCH (n:Donor {donor_id: 'SMC038'}) MATCH (c:CellCluster {leiden_id: 11}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 5.9101, r.n_cells = 213, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC039'}) MATCH (c:CellCluster {leiden_id: 11}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 3.75817, r.n_cells = 69, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC041'}) MATCH (c:CellCluster {leiden_id: 11}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 8.033241, r.n_cells = 377, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC043'}) MATCH (c:CellCluster {leiden_id: 11}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 0.470958, r.n_cells = 6, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC049'}) MATCH (c:CellCluster {leiden_id: 11}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 7.330002, r.n_cells = 484, r.condition = 'AD';
MATCH (n:Donor {donor_id: 'SMC052'}) MATCH (c:CellCluster {leiden_id: 11}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 3.456163, r.n_cells = 272, r.condition = 'Control';
MATCH (n:Donor {donor_id: 'SMC053'}) MATCH (c:CellCluster {leiden_id: 11}) MERGE (n)-[r:HAS_CLUSTER_PCT]->(c) ON CREATE SET r.pct = 9.129154, r.n_cells = 434, r.condition = 'Active control';

